name: first_test_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.1
  timezone: 0.9.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Logo oluşturucu paketi ekledik
  flutter_launcher_icons: ^0.13.1 

# Logo ayarlarını tanımladık
flutter_icons:
  android: true
  ios: true
  image_path: "img/logo.png" # Kendi logonun tam yolunu buraya yaz

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/Icons/
    - img/assets/audio/